[workspace]
members = [
    "modules/eth-token",
    "modules/eth-block-producers",
    "modules/pancakeswap",
    "modules/sol-spl-tokens",
    "modules/uniswap",
]

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"
